version: 0.2

phases:
  pre_build:
    commands:
  # test system variables
       - echo $AWS_DEFAULT_REGION 
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
       # variable defined in job
       - echo $Var1
       - ARTIFACT = codebuild-0.0.1-SNAPSHOT
       - ARTIFACT_TYPE = .jar 
       - echo $ ARTIFACT
       - echo $ ARTIFACT_TYPE
     
  build:
    commands:
     # testing both maven and gradle build
      - echo Gradle Build
      - chmod +x gradlew
      - ./gradlew  build
      
      - echo Maven Build 
      - mvn package
           
  post_build:
    commands:
     - echo Building the Docker image...  
      - REPOSITORY_URI=016973021151.dkr.ecr.eu-west-3.amazonaws.com/ecs-repository        
      - docker build -t $REPOSITORY_URI:latest .

artifacts:
     files:  codebuild-0.0.1-SNAPSHOT.jar