version: 0.2

phases:
  pre_build:
    commands:

     
  build:
    commands:

      #- echo Gradle Build
      #- chmod +x gradlew
      #- ./gradlew --debug --stacktrace build

      - echo Maven Build 
      - mvn package
           
  post_build:
    commands:

artifacts:
     files:  target/cbtest1-0.0.1-SNAPSHOT.jar