version: 0.2

phases:
  pre_build:
    commands:
  # test system variables
       - echo $AWS_DEFAULT_REGION 
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
       # variable defined in job
       - echo $Var1
       - ARTIFACT=codebuild-0.0.1-SNAPSHOT
       - ARTIFACT_TYPE=.jar 
       - echo $ARTIFACT
       - echo $ARTIFACT_TYPE
     
  build:
    commands:
     # testing both maven and gradle build
       - echo Gradle Build
       - chmod +x gradlew
       - ./gradlew  build
      
       - echo Maven Build 
       - mvn package
           
  post_build:
    commands:

artifacts:
     files:  target/codebuild-0.0.1-SNAPSHOT.jar